kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: todo-assessment
spec:
  scaleTargetRef:
    kind: Deployment
    name: todo-assessment
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
